version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bve1rk8vpndq"
s3_prefix = "sam-lambda"
region = "us-east-1"
profile = "csx"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ExecEnv=\"Prod\""
image_repositories = []
