AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  This is a SAM template for the sam-lambda functionality
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Parameters:
  ExecEnv:
    Type: String
    AllowedValues:
      - local
      - dev
      - stage
      - Prod
    Default: Prod

Resources:

  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref ExecEnv
      CorsConfiguration:
        AllowOrigins:
          - "http://*"
          - "https://*"
        AllowHeaders:
          - "'*'"
        AllowMethods:
          - "GET"
          - "POST"
          - "DELETE"
          - "PUT"
          - "OPTIONS"          
        MaxAge: 600

  SayHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: say-hello.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          REGION_NAME: !Ref AWS::Region
          EXEC_ENV: !Ref ExecEnv
      Events:
        SayHello:
          Type: HttpApi
          Properties:
            Path: /hello
            Method: get
            ApiId: !Ref Api

  FetchS3BucketsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: fetch-s3-buckets.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          REGION_NAME: !Ref AWS::Region
          EXEC_ENV: !Ref ExecEnv
      Policies:
      - Statement:
        - Sid: S3Permissions
          Effect: Allow
          Action:
          - s3:ListAllMyBuckets
          Resource: '*'
        - Sid: CloudWatchPermissions
          Effect: Allow
          Action:
          - "cloudwatch:GetMetricData"
          Resource: '*'
      Events:
        FetchS3Buckets:
          Type: HttpApi
          Properties:
            Path: /fetch-s3-buckets
            Method: get
            ApiId: !Ref Api 
            
  FetchSpecificCloudWatchMetricsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: fetch-specific-cloudwatch-metrics.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          REGION_NAME: !Ref AWS::Region
          EXEC_ENV: !Ref ExecEnv
      Policies:
      - Statement:
        - Sid: CloudWatchPermissions
          Effect: Allow
          Action:
          - "cloudwatch:GetMetricData"
          Resource: '*'
      Events:
        FetchSpecificCloudWatchMetrics:
          Type: HttpApi
          Properties:
            Path: /fetch-specific-cloudwatch-metrics
            Method: get      
            ApiId: !Ref Api 
                 
  FetchCloudWatchMetricsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: fetch-cloudwatch-metrics.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          REGION_NAME: !Ref AWS::Region
          EXEC_ENV: !Ref ExecEnv
      Policies:
      - Statement:
        - Sid: CloudWatchPermissions
          Effect: Allow
          Action:
          - "cloudwatch:GetMetricData"
          Resource: '*'
      Events:          
        FetchCloudWatchMetrics:
          Type: HttpApi
          Properties:
            Path: /fetch-cloudwatch-metrics
            Method: post
            ApiId: !Ref Api                          
  


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  Api:
    Description: "API Gateway endpoint URL for Prod stage for SAM Lambda function"
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"
  #Function:
  #  Description: "SAM Lambda Lambda Function ARN"
  #  Value: !GetAtt Function.Arn
  #FunctionIamRole:
  #  Description: "Implicit IAM Role created for SAM Lambda function"
  #  Value: !GetAtt FunctionRole.Arn