AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  This is a SAM template for the sam-lambda functionality
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: python3.9
    Timeout: 60    
    MemorySize: 3072
    Environment:
      Variables:
        REGION_NAME: !Ref AWS::Region
        SIGNATURE_VERSION: 'v4'
        RETRIES_MAX_ATTEMPTS: 10
        RETRIES_MODE: 'standard'
        EXEC_ENV: !Ref ExecEnv

Parameters:
  ExecEnv:
    Type: String
    AllowedValues:
      - local
      - dev
      - stage
      - Prod
    Default: Prod

Resources:

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref ExecEnv
      Cors:
        AllowMethods: "'POST, GET, DELETE, PUT, OPTIONS'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"

  ListCloudWatchNamespacesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: list-cloudwatch-namespaces
      Description: Lambda to list CloudWatch namespaces  
      CodeUri: app/cloudwatch    
      Handler: list-cloudwatch-namespaces.lambda_handler
      Policies:
      - Statement:
        - Sid: CloudWatchPermissions
          Effect: Allow
          Action:
          - "cloudwatch:ListMetrics"
          Resource: '*'      
      Events:
        ListNamespaces:
          Type: Api
          Properties:
            Path: /list-cloudwatch-namespaces
            Method: get      
            RestApiId: !Ref Api   

  ListCloudWatchMetricsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: list-cloudwatch-metrics
      Description: Lambda to list CloudWatch metrics      
      CodeUri: app/cloudwatch  
      Handler: list-cloudwatch-metrics.lambda_handler
      Policies:
      - Statement:
        - Sid: CloudWatchPermissions
          Effect: Allow
          Action:
          - "cloudwatch:ListMetrics"
          Resource: '*'      
      Events:
        ListMetrics:
          Type: Api
          Properties:
            Path: /list-cloudwatch-metrics
            Method: get      
            RestApiId: !Ref Api      

  FetchCloudWatchMetrics:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: fetch-cloudwatch-metrics
      Description: Lambda to fetch CloudWatch metrics
      CodeUri: app/cloudwatch  
      Handler: fetch-cloudwatch-metrics.lambda_handler
      Policies:
      - Statement:
        - Sid: CloudWatchPermissions
          Effect: Allow
          Action:
          - "cloudwatch:GetMetricData"
          Resource: '*'      
      Events:
        FetchCloudWatchMetrics:
          Type: Api
          Properties:
            Path: /fetch-cloudwatch-metrics
            Method: post      
            RestApiId: !Ref Api 

  ListSagemakerTrainingJobs:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: list-sagemaker-training-jobs
      Description: Lambda to list the Sagemaker training jobs
      CodeUri: app/sagemaker  
      Handler: list-sagemaker-training-jobs.lambda_handler
      Policies:
      - Statement:
        - Sid: SageMakerPermissions
          Effect: Allow
          Action:
          - "sagemaker:ListTrainingJobs"
          Resource: '*'      
      Events:
        ListSagemakerTrainingJobs:
          Type: Api
          Properties:
            Path: /sagemaker/list-training-jobs
            Method: get      
            RestApiId: !Ref Api 

  DescribeSagemakerTrainingJob:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: describe-sagemaker-training-job
      Description: Lambda to describe a Sagemaker training job
      CodeUri: app/sagemaker  
      Handler: describe-sagemaker-training-job.lambda_handler
      Policies:
      - Statement:
        - Sid: SageMakerPermissions
          Effect: Allow
          Action:
          - "sagemaker:DescribeTrainingJob"
          Resource: '*'      
      Events:
        DescribeSagemakerTrainingJob:
          Type: Api
          Properties:
            Path: /sagemaker/describe-training-job
            Method: get      
            RestApiId: !Ref Api 
       
  FetchOpsGenieAlerts:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: fetch-opsgenie-alerts
      Description: Lambda to fetch all OpsGenie alerts
      CodeUri: app/opsgenie  
      Handler: fetch-opsgenie-alerts.lambda_handler
      Environment:
         Variables:
           OPSGENIE_API_KEY_PARAM: 'OPSGENIE_API_KEY'
      Policies:
      - Statement:
        - Sid: OpsGeniePermissions
          Effect: Allow
          Action:
          - "ssm:GetParameter"
          Resource: '*'      
      Events:
        CreateOpsGenieAlert:
          Type: Api
          Properties:
            Path: /opsgenie/fetch-alerts
            Method: get      
            RestApiId: !Ref Api      
            
  CreateOpsGenieAlert:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: create-opsgenie-alert
      Description: Lambda to create an OpsGenie alert
      CodeUri: app/opsgenie  
      Handler: create-opsgenie-alert.lambda_handler
      Environment:
         Variables:
           OPSGENIE_API_KEY_PARAM: 'OPSGENIE_API_KEY'      
      Policies:
      - Statement:
        - Sid: OpsGeniePermissions
          Effect: Allow
          Action:
          - "ssm:GetParameter"
          Resource: '*'      
      Events:
        CreateOpsGenieAlert:
          Type: Api
          Properties:
            Path: /opsgenie/create-alert
            Method: post      
            RestApiId: !Ref Api    
            
  SendOpsGenieAlertEmail:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: send-opsgenie-alert-email
      Description: Lambda to send an OpsGenie alert email
      CodeUri: app/opsgenie  
      Handler: send-opsgenie-alert-email.lambda_handler 
      Events:
        SendOpsGenieAlertEmail:
          Type: Api
          Properties:
            Path: /opsgenie/send-alert-email
            Method: post      
            RestApiId: !Ref Api             
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BaseApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for SAM Lambda function"
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  #Function:
  #  Description: "SAM Lambda Lambda Function ARN"
  #  Value: !GetAtt Function.Arn
  #FunctionIamRole:
  #  Description: "Implicit IAM Role created for SAM Lambda function"
  #  Value: !GetAtt FunctionRole.Arn