AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  This is a SAM template for the sam-lambda functionality
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    Runtime: python3.9
    CodeUri: app/
    Environment:
      Variables:
        REGION_NAME: !Ref AWS::Region
        EXEC_ENV: !Ref ExecEnv

Parameters:
  ExecEnv:
    Type: String
    AllowedValues:
      - local
      - dev
      - stage
      - Prod
    Default: Prod

Resources:

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref ExecEnv
      Cors:
        AllowMethods: "'POST, GET, DELETE, PUT, OPTIONS'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"

  SayHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: say-hello
      Description: Testing lambda by saying hello
      CodeUri: appTestLambdas/hello
      Handler: say-hello.lambda_handler
      Events:
        SayHello:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref Api

  FetchS3BucketsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: fetch-s3-buckets
      Description: Lambda to fetch the s3 buckets - used for testing
      CodeUri: appTestLambdas/s3
      Handler: fetch-s3-buckets.lambda_handler
      Policies:
      - Statement:
        - Sid: S3Permissions
          Effect: Allow
          Action:
          - s3:ListAllMyBuckets
          Resource: '*'
      Events:
        FetchS3Buckets:
          Type: Api
          Properties:
            Path: /fetch-s3-buckets
            Method: get
            RestApiId: !Ref Api 
            
  FetchSpecificCloudWatchMetricsFunction:
    Type: AWS::Serverless::Function
    Properties:      
      FunctionName: fetch-specific-cloudwatch-metrics
      Description: Test cloudwatch metrics calls
      Handler: fetch-specific-cloudwatch-metrics.lambda_handler
      Policies:
      - Statement:
        - Sid: CloudWatchPermissions
          Effect: Allow
          Action:
          - "cloudwatch:GetMetricData"
          Resource: '*'
      Events:
        FetchSpecificCloudWatchMetrics:
          Type: Api
          Properties:
            Path: /fetch-specific-cloudwatch-metrics
            Method: get      
            RestApiId: !Ref Api 
                 
  FetchCloudWatchMetricsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: fetch-cloudwatch-metrics
      Description: Test cloudwatch metrics calls - can take query parameters for configuration    
      Handler: fetch-cloudwatch-metrics.lambda_handler
      Policies:
      - Statement:
        - Sid: CloudWatchPermissions
          Effect: Allow
          Action:
          - "cloudwatch:GetMetricData"
          Resource: '*'      
      Events:          
        FetchCloudWatchMetrics:
          Type: Api
          Properties:
            Path: /fetch-cloudwatch-metrics
            Method: post
            RestApiId: !Ref Api                          
  
  FetchAirflowMetricsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: fetch-airflow-metrics
      Description: Lambda to fetch airflow CloudWatch metrics
      Handler: fetch-airflow-metrics.lambda_handler
      Policies:
      - Statement:
        - Sid: CloudWatchPermissions
          Effect: Allow
          Action:
          - "cloudwatch:GetMetricData"
          Resource: '*'      
      Events:
        FetchSpecificCloudWatchMetrics:
          Type: Api
          Properties:
            Path: /fetch-airflow-metrics
            Method: get      
            RestApiId: !Ref Api 
    
  FetchSagemakerMetricsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: fetch-sagemaker-metrics 
      Description: Lambda to fetch sagemaker CloudWatch metrics      
      Handler: fetch-sagemaker-metrics.lambda_handler
      Policies:
      - Statement:
        - Sid: CloudWatchPermissions
          Effect: Allow
          Action:
          - "cloudwatch:GetMetricData"
          Resource: '*'      
      Events:
        FetchSpecificCloudWatchMetrics:
          Type: Api
          Properties:
            Path: /fetch-sagemaker-metrics
            Method: get      
            RestApiId: !Ref Api 

  FetchLambdaMetricsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: fetch-lambda-metrics
      Description: Lambda to fetch lambda CloudWatch metrics      
      Handler: fetch-lambda-metrics.lambda_handler
      Policies:
      - Statement:
        - Sid: CloudWatchPermissions
          Effect: Allow
          Action:
          - "cloudwatch:GetMetricData"
          Resource: '*'      
      Events:
        FetchSpecificCloudWatchMetrics:
          Type: Api
          Properties:
            Path: /fetch-lambda-metrics
            Method: get      
            RestApiId: !Ref Api 

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  Api:
    Description: "API Gateway endpoint URL for Prod stage for SAM Lambda function"
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"
  #Function:
  #  Description: "SAM Lambda Lambda Function ARN"
  #  Value: !GetAtt Function.Arn
  #FunctionIamRole:
  #  Description: "Implicit IAM Role created for SAM Lambda function"
  #  Value: !GetAtt FunctionRole.Arn